
import { Character } from './types';

export const CHARACTERS: Character[] = [
  {
    id: '1',
    name: 'TRALALERO TRALALA',
    description: 'Il chante des sons incompréhensibles et tout le monde adore.',
    story: 'Né dans les profondeurs de TikTok en 2024, Tralalero Tralala est apparu un jour dans une vidéo italienne sans aucune explication. Sa mélodie hypnotique "Tralalero Tralala" a conquis des millions de cerveaux. On raconte qu\'il était autrefois un requin normal de la Méditerranée, mais qu\'après avoir avalé un téléphone jouant de la musique en boucle, il s\'est transformé en cette créature virale. Il vit désormais entre deux dimensions : le monde réel et l\'algorithme. Son but ultime ? Que chaque être humain fredonne sa chanson au moins une fois.',
    imageUrl: '/images/tralalero-tralala.webp',
    tags: ['Musique', 'Viral', 'Mystérieux', 'Aquatique'],
    rarity: 'Legendary',
    species: 'Animal',
    element: 'Sonore',
    alignment: 'Neutre',
    size: 'Grand',
    origin: 'Mer Méditerranée / TikTok',
    power: 'Hypnose musicale - sa mélodie reste dans la tête pendant des semaines',
    weakness: 'Le silence absolu le fait disparaître temporairement'
  },
  {
    id: '2',
    name: 'BOMBARDIRO CROCODILO',
    description: 'Mi-avion, mi-crocodile. 100% destruction.',
    story: 'Bombardiro Crocodilo est le résultat d\'une expérience militaire italienne ultra-secrète qui a mal tourné. En 1987, l\'armée a tenté de créer l\'arme ultime en fusionnant un crocodile du Nil avec un bombardier B-52. L\'expérience a réussi... trop bien. Bombardiro s\'est échappé et vit maintenant dans les marécages de Vénétie, d\'où il décolle chaque nuit pour larguer des bombes de chaos sur les villes endormies. Il est considéré comme le père fondateur de toute la lignée des brainrots hybrides.',
    imageUrl: '/images/bombardiro-crocodilo.jpg',
    tags: ['Avion', 'Crocodile', 'Explosif', 'Militaire'],
    rarity: 'Legendary',
    species: 'Hybride',
    element: 'Feu',
    alignment: 'Chaotique',
    size: 'Géant',
    origin: 'Laboratoire militaire italien',
    power: 'Vol supersonique + mâchoires d\'acier + bombes intégrées',
    weakness: 'Les radars anti-aériens le rendent nerveux'
  },
  {
    id: '3',
    name: 'BRR BRR PATAPIM',
    description: 'Il fait des bruits bizarres et personne sait pourquoi.',
    story: 'Brr Brr Patapim est une anomalie sonore qui a pris forme physique. Personne ne sait exactement d\'où il vient, mais les théories suggèrent qu\'il est né de la fusion de tous les bruits de notification de téléphone du monde entier. Il communique uniquement par onomatopées : "Brr", "Patapim", "Ding", "Swoosh". Les scientifiques ont tenté de le décoder pendant des années, sans succès. Il danse constamment, même quand il dort (oui, il dort en dansant). Son rêve est de devenir le son de notification par défaut de tous les téléphones.',
    imageUrl: '/images/brr-brr-patapim.jpg',
    tags: ['Bruit', 'Étrange', 'Danseur', 'Notification'],
    rarity: 'Legendary',
    species: 'Créature',
    element: 'Sonore',
    alignment: 'Chaotique',
    size: 'Moyen',
    origin: 'La dimension des notifications',
    power: 'Peut reproduire n\'importe quel son et faire danser involontairement',
    weakness: 'Le mode silencieux le paralyse'
  },
  {
    id: '4',
    name: 'TUNG TUNG SAHUR',
    description: 'Il te réveille à 3h du mat avec des percussions.',
    story: 'Tung Tung Sahur est l\'incarnation vivante du réveil brutal. Originaire d\'Indonésie, il était autrefois un simple tambour utilisé pendant le Ramadan pour réveiller les gens pour le Sahur (repas avant l\'aube). Mais après des décennies de service, le tambour a absorbé tellement de frustration de gens réveillés qu\'il a pris vie. Maintenant, il parcourt le monde entier, apparaissant sans prévenir à 3h du matin pour jouer ses percussions infernales. "TUNG TUNG TUNG TUNG TUNG!" - personne n\'échappe à son rythme.',
    imageUrl: '/images/tung-tung-sahur.jpg',
    tags: ['Percussion', 'Réveil', 'Chaotique', 'Nocturne'],
    rarity: 'Rare',
    species: 'Objet',
    element: 'Sonore',
    alignment: 'Chaotique',
    size: 'Moyen',
    origin: 'Indonésie',
    power: 'Réveille n\'importe qui, n\'importe où, à n\'importe quelle heure',
    weakness: 'Les boules Quies de qualité militaire'
  },
  {
    id: '5',
    name: 'CAPPUCCINO ASSASSINO',
    description: 'Le café qui tue. Littéralement.',
    story: 'Dans un petit café de Naples, un barista a préparé un cappuccino si fort, si concentré, si INTENSE qu\'il a pris conscience. Cappuccino Assassino est né ce jour-là, jurant de punir tous ceux qui osent mettre du lait d\'avoine dans leur espresso. C\'est un tueur à gages caféiné qui travaille exclusivement la nuit (forcément, il ne peut pas dormir). Son arme ? Une dose létale de caféine pure injectée directement dans le cerveau de ses victimes. Ironie du sort : il déteste le goût du café décaféiné.',
    imageUrl: '/images/cappuccino-assassino.jpg',
    tags: ['Café', 'Assassin', 'Dangereux', 'Nocturne'],
    rarity: 'Rare',
    species: 'Objet',
    element: 'Café',
    alignment: 'Maléfique',
    size: 'Petit',
    origin: 'Naples, Italie',
    power: 'Injection de caféine mortelle + insomnie contagieuse',
    weakness: 'L\'eau chaude le dilue et l\'affaiblit'
  },
  {
    id: '6',
    name: 'BALLERINA CAPPUCCINA',
    description: 'Elle danse dans ta tasse de café le matin.',
    story: 'Ballerina Cappuccina était une danseuse étoile de la Scala de Milan qui, un matin, est tombée dans une tasse de cappuccino géante pendant une représentation surréaliste. Au lieu de se noyer, elle a fusionné avec la mousse de lait et est devenue une créature mi-ballerine, mi-café. Elle apparaît désormais dans les tasses de café du monde entier, exécutant des pirouettes parfaites sur la crema. Elle est la cousine bienveillante de Cappuccino Assassino, et tente de répandre la joie plutôt que la mort.',
    imageUrl: '/images/ballerina-cappuccina.jpg',
    tags: ['Danse', 'Café', 'Élégante', 'Artistique'],
    rarity: 'Common',
    species: 'Hybride',
    element: 'Café',
    alignment: 'Gentil',
    size: 'Petit',
    origin: 'La Scala de Milan',
    power: 'Danse hypnotique + peut transformer n\'importe quel liquide en café',
    weakness: 'Les tasses mal lavées la dépriment'
  },
  {
    id: '7',
    name: 'BANDITO BOBRITTO',
    description: 'Le castor bandit qui vole tes logs.',
    story: 'Bandito Bobritto est le castor le plus recherché d\'Europe. Né dans les forêts de Lombardie, il a développé très jeune un goût pour le crime. Mais pas n\'importe quel crime : il vole exclusivement du bois. Troncs, planches, allumettes, crayons - rien n\'est à l\'abri. Il porte un sombrero et un bandana par pure esthétique (il n\'a jamais mis les pattes au Mexique). Son gang, "Los Castoritos", terrorise les scieries de toute l\'Italie du Nord. Son rêve ? Construire le plus grand barrage illégal du monde.',
    imageUrl: '/images/bandito-bobritto.jpeg',
    tags: ['Castor', 'Bandit', 'Voleur', 'Bois'],
    rarity: 'Rare',
    species: 'Animal',
    element: 'Terre',
    alignment: 'Chaotique',
    size: 'Petit',
    origin: 'Forêts de Lombardie',
    power: 'Peut ronger n\'importe quel matériau + discrétion absolue',
    weakness: 'Le plastique - il ne peut pas le ronger et ça le frustre'
  },
  {
    id: '8',
    name: 'BOMBOMBINI GUSINI',
    description: 'Il explose tout sur son passage. Boom boom.',
    story: 'Bombombini Gusini est un accident de laboratoire devenu légende. Un chimiste distrait a mélangé de la nitroglycérine avec de la pâte à gnocchi, créant une créature instable qui explose à la moindre émotion forte. Joie ? BOOM. Tristesse ? BOOM. Léger agacement ? MEGA BOOM. Miraculeusement, il survit toujours à ses propres explosions et se reconstitue en quelques secondes. Il vit dans une grotte isolée des Dolomites, car personne ne veut l\'avoir comme voisin. Son hobby ? Regarder des films d\'action (avec beaucoup d\'explosions, évidemment).',
    imageUrl: '/images/bombombini-gusini.jpg',
    tags: ['Explosion', 'Bombe', 'Danger', 'Instable'],
    rarity: 'Rare',
    species: 'Créature',
    element: 'Feu',
    alignment: 'Neutre',
    size: 'Moyen',
    origin: 'Laboratoire des Dolomites',
    power: 'Auto-explosion illimitée + régénération instantanée',
    weakness: 'La méditation le stabilise (mais il n\'arrive jamais à méditer)'
  },
  {
    id: '9',
    name: 'CHIMPANZINI BANANINI',
    description: 'Le singe qui lance des bananes à la vitesse du son.',
    story: 'Chimpanzini Bananini était un chimpanzé ordinaire du zoo de Rome jusqu\'au jour où il a mangé une banane radioactive tombée d\'un satellite soviétique. Depuis, il peut lancer des bananes à Mach 3. Il a été banni de tous les zoos du monde après avoir assommé 47 visiteurs en une seule journée. Il vit maintenant dans les arbres du parc de la Villa Borghese, d\'où il snipe les touristes imprudents. Malgré sa violence fruitière, il est végétarien et milite pour les droits des primates.',
    imageUrl: '/images/chimpanzini-bananini.jpeg',
    tags: ['Singe', 'Banane', 'Rapide', 'Projectile'],
    rarity: 'Common',
    species: 'Animal',
    element: 'Air',
    alignment: 'Chaotique',
    size: 'Moyen',
    origin: 'Zoo de Rome',
    power: 'Lance des bananes à Mach 3 avec une précision mortelle',
    weakness: 'Les allergies au pollen au printemps'
  },
  {
    id: '10',
    name: 'ESPRESSONA SIGNORA',
    description: 'La dame du café ultra-concentré. Elle ne dort jamais.',
    story: 'Espressona Signora est une vieille dame napolitaine qui n\'a pas dormi depuis 1973. Cette année-là, elle a bu un espresso tellement fort qu\'elle est entrée dans un état permanent d\'éveil. Cinquante ans plus tard, elle a fusionné avec la caféine elle-même. Elle passe ses nuits (et ses jours) à préparer le café parfait, une quête sans fin qui l\'a rendue légèrement folle. Elle parle à une vitesse impossible et peut voir dans le futur (mais seulement les événements liés au café). C\'est la matriarche de la famille Café.',
    imageUrl: '/images/espressona-signora.jpg',
    tags: ['Café', 'Dame', 'Insomnie', 'Ancienne'],
    rarity: 'Common',
    species: 'Humanoïde',
    element: 'Café',
    alignment: 'Gentil',
    size: 'Moyen',
    origin: 'Naples, Italie',
    power: 'Vision du futur caféiné + préparation du café parfait',
    weakness: 'Le thé la met en colère irrationnelle'
  },
  {
    id: '11',
    name: 'GIRAFFA CELESTE',
    description: 'La girafe qui vient du ciel. Personne sait comment.',
    story: 'Un jour de 2019, une girafe bleue est tombée du ciel au-dessus de Florence. Pas de parachute, pas d\'avion, juste... une girafe. Elle a atterri en douceur sur le Duomo et n\'a jamais expliqué d\'où elle venait. Les scientifiques pensent qu\'elle vient d\'une dimension parallèle où toutes les girafes sont bleues et peuvent voler. Elle communique par télépathie, mais uniquement pour partager des pensées philosophiques profondes et des memes. Elle est considérée comme une déesse par un petit culte de 47 personnes à Pise.',
    imageUrl: '/images/giraffa-celeste.jpg',
    tags: ['Girafe', 'Ciel', 'Mystique', 'Bleue'],
    rarity: 'Rare',
    species: 'Animal',
    element: 'Air',
    alignment: 'Gentil',
    size: 'Géant',
    origin: 'Dimension parallèle / Florence',
    power: 'Télépathie + lévitation + sagesse cosmique',
    weakness: 'Les portes basses (elle se cogne toujours)'
  },
  {
    id: '12',
    name: 'LA VACCA SATURNO SATURNITA',
    description: 'La vache qui vient de Saturne. Elle fait du lait cosmique.',
    story: 'La Vacca Saturno Saturnita est arrivée sur Terre en 1969, exactement au moment où Neil Armstrong marchait sur la Lune. Coïncidence ? Absolument pas. Elle faisait partie d\'un programme d\'échange intergalactique entre Saturne et la Terre. Son lait cosmique contient des particules d\'anneaux de Saturne et confère des visions de l\'univers à quiconque le boit. Elle vit dans une ferme secrète de Toscane, protégée par le gouvernement italien. Son meuglement peut être entendu depuis l\'espace.',
    imageUrl: '/images/la-vacca-saturno-saturnita.jpg',
    tags: ['Vache', 'Saturne', 'Cosmique', 'Espace'],
    rarity: 'Legendary',
    species: 'Animal',
    element: 'Cosmique',
    alignment: 'Gentil',
    size: 'Grand',
    origin: 'Saturne',
    power: 'Lait cosmique hallucinogène + communication interstellaire',
    weakness: 'La gravité terrestre la fatigue'
  },
  {
    id: '13',
    name: 'LIRILÌ LARILÀ',
    description: 'Il chante en boucle. Impossible de l\'arrêter.',
    story: 'Lirilì Larilà est une malédiction musicale qui a pris forme. Née d\'une chanson italienne des années 60 qui passait en boucle dans un ascenseur pendant 40 ans, cette créature ne peut physiquement pas s\'arrêter de chanter. "Lirilì Larilà, Larilà Lirilì" - c\'est tout ce qu\'elle sait dire. Elle erre dans les centres commerciaux et les aéroports, condamnée à chanter pour l\'éternité. Certains disent que si on arrive à chanter avec elle pendant 24 heures non-stop, elle accorde un vœu. Personne n\'a jamais réussi.',
    imageUrl: '/images/lirili-larila.jpg',
    tags: ['Chant', 'Boucle', 'Infini', 'Malédiction'],
    rarity: 'Common',
    species: 'Créature',
    element: 'Sonore',
    alignment: 'Neutre',
    size: 'Moyen',
    origin: 'Un ascenseur à Milan',
    power: 'Chant infini + peut exaucer un vœu (théoriquement)',
    weakness: 'Les écouteurs antibruit la rendent triste'
  },
  {
    id: '14',
    name: 'PIRI PIRI CROCODILLINI',
    description: 'Le petit cousin épicé de Bombardiro.',
    story: 'Piri Piri Crocodillini est le petit cousin de Bombardiro Crocodilo, mais au lieu d\'être fusionné avec un avion, il a été fusionné avec un piment. Résultat : un mini-crocodile qui crache du feu et dont la morsure cause une sensation de brûlure intense pendant 3 jours. Il souffre d\'un complexe d\'infériorité par rapport à son cousin célèbre et essaie constamment de prouver qu\'il est tout aussi dangereux. Il vit dans les cuisines de restaurants italiens, sabotant les plats qu\'il juge "pas assez épicés".',
    imageUrl: '/images/piri-piri-crocodillini.jpg',
    tags: ['Crocodile', 'Épicé', 'Petit', 'Feu'],
    rarity: 'Common',
    species: 'Hybride',
    element: 'Feu',
    alignment: 'Chaotique',
    size: 'Petit',
    origin: 'Cuisine d\'un restaurant à Calabre',
    power: 'Souffle de feu épicé + morsure brûlante',
    weakness: 'Le lait éteint ses flammes et le rend inoffensif'
  },
  {
    id: '15',
    name: 'PUSSINI SUSHINI',
    description: 'Le chat-sushi. Il nage dans la sauce soja.',
    story: 'Pussini Sushini est né quand un chat de gouttière romain est tombé dans une cuve de riz à sushi d\'un restaurant japonais de Trastevere. La fusion a créé un être mi-félin, mi-maki qui sent perpétuellement le poisson frais. Il passe ses journées à nager dans des bols géants de sauce soja et à miauler des haïkus. C\'est le seul brainrot d\'origine italo-japonaise, ce qui lui confère un statut diplomatique spécial. Il déteste le wasabi car ça lui pique le nez.',
    imageUrl: '/images/pussini-sushini.jpg',
    tags: ['Chat', 'Sushi', 'Japon', 'Poisson'],
    rarity: 'Rare',
    species: 'Hybride',
    element: 'Eau',
    alignment: 'Neutre',
    size: 'Petit',
    origin: 'Restaurant japonais à Rome',
    power: 'Peut transformer n\'importe quoi en sushi + 9 vies',
    weakness: 'Le wasabi - allergie sévère'
  },
  {
    id: '16',
    name: 'TIGRULLINI WATERMELINI',
    description: 'Le tigre-pastèque. Frais et dangereux.',
    story: 'Tigrullini Watermelini est apparu lors d\'une canicule record en Sicile en 2023. Un tigre du cirque local, déshydraté, a plongé dans un champ de pastèques et en est ressorti transformé. Sa fourrure est maintenant verte avec des rayures rouges, et il sent le melon frais. Malgré son apparence rafraîchissante, il reste un prédateur redoutable. Il chasse uniquement en été et hiberne dans un congélateur industriel le reste de l\'année. Son rugissement fait le bruit d\'une pastèque qu\'on coupe.',
    imageUrl: '/images/tigrullini-watermelini.jpg',
    tags: ['Tigre', 'Pastèque', 'Été', 'Frais'],
    rarity: 'Common',
    species: 'Hybride',
    element: 'Eau',
    alignment: 'Neutre',
    size: 'Grand',
    origin: 'Sicile',
    power: 'Rafraîchit tout ce qu\'il touche + griffes de glace',
    weakness: 'L\'hiver le rend léthargique'
  },
  {
    id: '17',
    name: 'TRULIMERO TRULICINA',
    description: 'Les jumeaux du chaos. Double problème.',
    story: 'Trulimero et Trulicina sont des jumeaux nés d\'une erreur de copier-coller cosmique. Quand l\'univers a créé Trulimero, il a accidentellement appuyé sur Ctrl+V et Trulicina est apparue. Ils sont identiques mais opposés : quand l\'un dit oui, l\'autre dit non. Quand l\'un avance, l\'autre recule. Ils sont constamment en désaccord mais ne peuvent pas être séparés de plus de 10 mètres sans exploser. Ensemble, ils créent un champ de chaos qui rend fou quiconque reste trop longtemps près d\'eux.',
    imageUrl: '/images/trulimero-trulicina.jpg',
    tags: ['Jumeaux', 'Chaos', 'Double', 'Opposés'],
    rarity: 'Rare',
    species: 'Créature',
    element: 'Cosmique',
    alignment: 'Chaotique',
    size: 'Moyen',
    origin: 'Erreur de l\'univers',
    power: 'Champ de chaos + inversion de la réalité locale',
    weakness: 'Les miroirs les confondent et les paralysent'
  }
];
